//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpriteBoy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpriteBoy.ControlStrings", typeof(ControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete file?
        ///%FILE%.
        /// </summary>
        internal static string DeleteFileText {
            get {
                return ResourceManager.GetString("DeleteFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string DeleteFileTitle {
            get {
                return ResourceManager.GetString("DeleteFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete folder?
        ///%FOLDER%.
        /// </summary>
        internal static string DeleteFolderText {
            get {
                return ResourceManager.GetString("DeleteFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        internal static string DeleteFolderTitle {
            get {
                return ResourceManager.GetString("DeleteFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string DialogAbortButton {
            get {
                return ResourceManager.GetString("DialogAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancelButton {
            get {
                return ResourceManager.GetString("DialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string DialogIgnoreButton {
            get {
                return ResourceManager.GetString("DialogIgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogNoButton {
            get {
                return ResourceManager.GetString("DialogNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogOKButton {
            get {
                return ResourceManager.GetString("DialogOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string DialogRetryButton {
            get {
                return ResourceManager.GetString("DialogRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogYesButton {
            get {
                return ResourceManager.GetString("DialogYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpriteBoy can&apos;t find special editor for file:
        ///
        ///%FILE%
        ///
        ///Please, use specialized software to edit this type of file..
        /// </summary>
        internal static string EditorNotFoundText {
            get {
                return ResourceManager.GetString("EditorNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file.
        /// </summary>
        internal static string EditorNotFoundTitle {
            get {
                return ResourceManager.GetString("EditorNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FileInfoFolder {
            get {
                return ResourceManager.GetString("FileInfoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files inside: %COUNT%.
        /// </summary>
        internal static string FileInfoFolderFiles {
            get {
                return ResourceManager.GetString("FileInfoFolderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File (%EXT%).
        /// </summary>
        internal static string FileInfoUnknown {
            get {
                return ResourceManager.GetString("FileInfoUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exist!.
        /// </summary>
        internal static string FileNameExists {
            get {
                return ResourceManager.GetString("FileNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains invalid characters!.
        /// </summary>
        internal static string FileNameIncorrect {
            get {
                return ResourceManager.GetString("FileNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string InspectorContextCopy {
            get {
                return ResourceManager.GetString("InspectorContextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new....
        /// </summary>
        internal static string InspectorContextCreate {
            get {
                return ResourceManager.GetString("InspectorContextCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string InspectorContextDelete {
            get {
                return ResourceManager.GetString("InspectorContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string InspectorContextFolder {
            get {
                return ResourceManager.GetString("InspectorContextFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string InspectorContextOpen {
            get {
                return ResourceManager.GetString("InspectorContextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string InspectorContextPaste {
            get {
                return ResourceManager.GetString("InspectorContextPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string InspectorContextRename {
            get {
                return ResourceManager.GetString("InspectorContextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files not found.
        /// </summary>
        internal static string InspectorEmptyMessage {
            get {
                return ResourceManager.GetString("InspectorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load project: 
        ///
        ///%PROJECT%
        ///
        ///Please, create new or locate it&apos;s folder if it was moved..
        /// </summary>
        internal static string ProjectNotFoundText {
            get {
                return ResourceManager.GetString("ProjectNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        internal static string ProjectNotFoundTitle {
            get {
                return ResourceManager.GetString("ProjectNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes before closing?.
        /// </summary>
        internal static string TabCloseText {
            get {
                return ResourceManager.GetString("TabCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing editor.
        /// </summary>
        internal static string TabCloseTitle {
            get {
                return ResourceManager.GetString("TabCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current file has been changed outside of an application. Would you like to reload changes from disk?.
        /// </summary>
        internal static string TabReloadText {
            get {
                return ResourceManager.GetString("TabReloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed.
        /// </summary>
        internal static string TabReloadTitle {
            get {
                return ResourceManager.GetString("TabReloadTitle", resourceCulture);
            }
        }
    }
}
